### ISSUE TITLE
Incompatible with --simple-collections (both|only)

### ISSUE THREAD

**Issue by scyclow** [graphile/pg-simplify-inflector#14]
There seems to be an incompatibility when using `pg-simplify-inflector` with the `simple-collections` flag.

`postgraphile --append-plugins @graphile-contrib/pg-simplify-inflector --simple-collections both`
and
`postgraphile --append-plugins @graphile-contrib/pg-simplify-inflector --simple-collections only`
yield the following error:

```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "authoredPosts-list" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "posts-list" does not.
    at assertValidSchema (~/pg-test/node_modules/graphql/type/validate.js:71:11)
    at Object.validate (~/pg-test/node_modules/graphql/validation/validate.js:55:35)
    at parseQuery (~/pg-test/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:231:48)
    at Promise.all.paramsList.map (~/pg-test/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:483:63)
    at Array.map (<anonymous>)
    at requestHandler (~/pg-test/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:450:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

`--simple-collections omit` seems to work fine with the plugin.

**Comment by scyclow** [comment]
Should this be `List` instead of `-list`?
https://github.com/graphile-contrib/pg-simplify-inflector/blob/master/index.js#L183

**Comment by benjie** [comment]
Apologies; this is fixed [on master](https://github.com/graphile-contrib/pg-simplify-inflector/commit/c67657f2bfc9fbcd97861bc20bfeeca840363852) but I've not managed to get a new release out yet. I'll try to do so early in the new year; in the mean time you can just use the GitHub repo directly `yarn add https://github.com/graphile-contrib/pg-simplify-inflector.git`

**Comment by benjie** [comment]
Fixed on master

**Comment by benjie** [comment]
This is out in the latest version (it's an alpha, so beware).
